# Generated by Django 5.2.5 on 2025-08-10 13:21

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=100)),
                ('years', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('tasks', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=3)),
            ],
        ),
    ]
