# Generated by Django 5.2.5 on 2025-08-10 16:23

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('years', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('Institute', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
