# Generated by Django 5.2.5 on 2025-08-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_testupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUpload',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile',
            field=models.ImageField(upload_to='testimonial/'),
        ),
    ]
