# Generated by Django 5.2.5 on 2025-08-14 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_testupload_alter_testimonial_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='images_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=5),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile',
            field=models.ImageField(upload_to='media/testimonial/'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
