# Generated by Django 5.2.5 on 2025-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_eduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduction',
            name='field',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
