# Generated by Django 5.2.5 on 2025-08-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_project_image_project_images_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='profile',
            field=models.URLField(),
        ),
    ]
