# Generated by Django 5.2.5 on 2025-08-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_alter_testimonial_profile_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(default='', null=True),
        ),
    ]
